const EXPRESSION_CATEGORIES = [
  { key: "positive", label: "😊 positive" },
  { key: "care", label: "🤗 care & support" },
  { key: "playful", label: "😜 playful & silly" },
  { key: "neutral", label: "😐 neutral" },
  { key: "sad", label: "😢 sad & gloomy" },
  { key: "mean", label: "😈 mean & angry" },
  { key: "morning", label: "🌅 good morning" },
  { key: "night", label: "🌙 good night" },
  { key: "food", label: "🍽️ food & drinks" },
  { key: "animals", label: "🐾 animal vibes" },
  { key: "weather", label: "🌈 weather moods" },
  { key: "other", label: "✨ other" },
  { key: "reminder", label: "⏲️ reminders" },
];

const EXPRESSIONS = {
  // Positive
  hug: {
    emoji: "🤗",
    message: "sent you a warm hug!",
    label: "send a hug",
    category: "positive",
  },
  kiss: {
    emoji: "😘",
    message: "blew you a kiss!",
    label: "blow a kiss",
    category: "positive",
  },
  heart: {
    emoji: "❤️",
    message: "sent you love!",
    label: "send love",
    category: "positive",
  },
  cuddle: {
    emoji: "🫂",
    message: "wants to cuddle with you!",
    label: "cuddle",
    category: "positive",
  },
  smile: {
    emoji: "😊",
    message: "smiled at you!",
    label: "send a smile",
    category: "positive",
  },
  smile_back: {
    emoji: "😊",
    message: "smiled back at you warmly!",
    label: "smile back",
    category: "positive",
  },
  wink: {
    emoji: "😉",
    message: "winked at you!",
    label: "wink",
    category: "positive",
  },
  high_five: {
    emoji: "🙏",
    message: "gave you a high five!",
    label: "high five",
    category: "positive",
  },
  thumbs_up: {
    emoji: "👍",
    message: "gave you thumbs up!",
    label: "thumbs up",
    category: "positive",
  },
  clap: {
    emoji: "👏",
    message: "is clapping for you!",
    label: "clap",
    category: "positive",
  },
  handshake: {
    emoji: "🤝",
    message: "shook your hand!",
    label: "handshake",
    category: "positive",
  },
  wave: {
    emoji: "👋",
    message: "waved at you!",
    label: "wave",
    category: "positive",
  },
  cheer: {
    emoji: "🎉",
    message: "is cheering for you!",
    label: "cheer",
    category: "positive",
  },
  dance: {
    emoji: "💃",
    message: "is dancing with you!",
    label: "dance",
    category: "positive",
  },
  blush: {
    emoji: "😊",
    message: "blushed because of you!",
    label: "blush",
    category: "positive",
  },
  good_luck: {
    emoji: "🍀",
    message: "wished you good luck!",
    label: "wish good luck",
    category: "positive",
  },
  trophy: {
    emoji: "🏆",
    message: "thinks you deserve a trophy!",
    label: "deserve trophy",
    category: "positive",
  },
  fireworks: {
    emoji: "🎆",
    message: "is celebrating with fireworks!",
    label: "celebrate with fireworks",
    category: "positive",
  },
  admire: {
    emoji: "😍",
    message: "admires you greatly!",
    label: "admire",
    category: "positive",
  },
  gratitude: {
    emoji: "🙏",
    message: "is grateful to have you",
    label: "show gratitude",
    category: "positive",
  },
  share_happiness: {
    emoji: "🎈",
    message: "shared their happiness with you!",
    label: "share happiness",
    category: "positive",
  },

  // Care & Support
  umbrella: {
    emoji: "☂️",
    message: "offered you an umbrella!",
    label: "offer umbrella",
    category: "care",
  },
  fan: {
    emoji: "🪭",
    message: "offered you a fan!",
    label: "offer a fan",
    category: "care",
  },
  blanket: {
    emoji: "🛏️",
    message: "wrapped you in a warm blanket!",
    label: "warm blanket",
    category: "care",
  },
  medicine: {
    emoji: "💊",
    message: "brought you medicine!",
    label: "bring medicine",
    category: "care",
  },
  bandaid: {
    emoji: "🩹",
    message: "put a band-aid on your boo-boo!",
    label: "put a band-aid",
    category: "care",
  },
  shield: {
    emoji: "🛡️",
    message: "is protecting you!",
    label: "protect",
    category: "care",
  },
  support: {
    emoji: "🫂",
    message: "is here to support you!",
    label: "support",
    category: "care",
  },
  listen: {
    emoji: "👂",
    message: "is here to listen to you",
    label: "listen",
    category: "care",
  },
  comfort: {
    emoji: "🫂",
    message: "is comforting you with a gentle hug",
    label: "comfort",
    category: "care",
  },
  share_emotions: {
    emoji: "💬",
    message: "wants to share their emotions with you.",
    label: "share emotions",
    category: "care",
  },
  offer_tissue: {
    emoji: "🤧",
    message: "offered you a tissue!",
    label: "offer tissue",
    category: "care",
  },
  plant_tree: {
    emoji: "🌱",
    message: "planted a friendship tree with you!",
    label: "plant tree",
    category: "care",
  },
  healing: {
    emoji: "💝",
    message: "sent healing energy your way",
    label: "send healing",
    category: "care",
  },
  proud: {
    emoji: "🌟",
    message: "is proud of you!",
    label: "be proud",
    category: "care",
  },
  strength: {
    emoji: "💪",
    message: "sends you strength",
    label: "send strength",
    category: "care",
  },
  warm_tea: {
    emoji: "🫖",
    message: "made you some warm tea!",
    label: "make tea",
    category: "care",
  },
  therapy: {
    emoji: "🛋️",
    message: "offered a listening ear",
    label: "therapy session",
    category: "care",
  },
  meditation_guide: {
    emoji: "🧘‍♀️",
    message: "helps you find inner peace",
    label: "help with meditation",
    category: "care",
  },
  encourage: {
    emoji: "💪",
    message: "encouraged you to keep going!",
    label: "encourage",
    category: "care",
  },
  reassure: {
    emoji: "🤗",
    message: "reassured you with kind words!",
    label: "reassure",
    category: "care",
  },
  guide: {
    emoji: "🧭",
    message: "guided you through the darkness!",
    label: "guide",
    category: "care",
  },
  build_fort: {
    emoji: "⛺",
    message: "built a cozy fort for you!",
    label: "build fort",
    category: "care",
  },
  check_in: {
    emoji: "📞",
    message: "checked in to see how you're doing!",
    label: "check in",
    category: "care",
  },
  hold_hand: {
    emoji: "✋",
    message: "held your hand for comfort!",
    label: "hold hand",
    category: "care",
  },
  warm_meal: {
    emoji: "🍲",
    message: "prepared a warm meal for you!",
    label: "prepare meal",
    category: "care",
  },
  safe_space: {
    emoji: "🏠",
    message: "created a safe space for you!",
    label: "safe space",
    category: "care",
  },
  stay_by_side: {
    emoji: "🛋️",
    message: "stayed by your side through tough times!",
    label: "stay by side",
    category: "care",
  },

  // Playful
  tickle: {
    emoji: "🤗",
    message: "is tickling you!",
    label: "tickle",
    category: "playful",
  },
  silly_dance: {
    emoji: "👯",
    message: "is doing a silly dance!",
    label: "silly dance",
    category: "playful",
  },
  hide_under_bed: {
    emoji: "🛏️",
    message: "is hiding under the bed!",
    label: "hide under the bed",
    category: "playful",
  },
  pat: { emoji: "🐾", message: "pat you!", label: "pat", category: "playful" },
  boop: {
    emoji: "👉",
    message: "booped your nose!",
    label: "boop nose",
    category: "playful",
  },
  peek: {
    emoji: "👀",
    message: "is playing peek-a-boo!",
    label: "peek-a-boo",
    category: "playful",
  },
  microphone: {
    emoji: "🎤",
    message: "sang to you!",
    label: "sing",
    category: "playful",
  },
  detective: {
    emoji: "🕵️",
    message: "is investigating you!",
    label: "investigate",
    category: "playful",
  },
  bubble: {
    emoji: "🫧",
    message: "blew bubbles at you!",
    label: "blow bubbles",
    category: "playful",
  },
  pillow_fight: {
    emoji: "🛏️",
    message: "started a pillow fight!",
    label: "pillow fight",
    category: "playful",
  },
  ghost: {
    emoji: "👻",
    message: "spooked you playfully!",
    label: "spook",
    category: "playful",
  },
  juggle: {
    emoji: "🤹",
    message: "juggled to entertain you!",
    label: "juggle",
    category: "playful",
  },
  rollercoaster: {
    emoji: "🎢",
    message: "took you on a fun ride!",
    label: "fun ride",
    category: "playful",
  },
  magic_trick: {
    emoji: "🎩",
    message: "performed a magic trick!",
    label: "magic trick",
    category: "playful",
  },
  selfie: {
    emoji: "🤳",
    message: "took a silly selfie with you!",
    label: "take selfie",
    category: "playful",
  },
  splash: {
    emoji: "💦",
    message: "splashed water at you!",
    label: "splash",
    category: "playful",
  },
  playful_poke: {
    emoji: "👉",
    message: "playfully poked you!",
    label: "poke",
    category: "playful",
  },
  tickle_feather: {
    emoji: "🪶",
    message: "tickled you with a feather!",
    label: "tickle with feather",
    category: "playful",
  },
  bubble_wrap: {
    emoji: "🫧",
    message: "popped bubble wrap with you!",
    label: "pop bubble wrap",
    category: "playful",
  },

  // Neutral
  ask_attention: {
    emoji: "🥺",
    message: "wants your attention!",
    label: "ask for attention",
    category: "neutral",
  },
  fall_asleep: {
    emoji: "😴",
    message: "fell asleep on you!",
    label: "fall asleep on them",
    category: "neutral",
  },
  hungry: {
    emoji: "🤤",
    message: "is drooling with hunger!",
    label: "hungry",
    category: "neutral",
  },
  think: {
    emoji: "🤔",
    message: "is thinking about what you said...",
    label: "think about their words",
    category: "neutral",
  },
  reflect: {
    emoji: "🪞",
    message: "is reflecting on your words...",
    label: "reflect on their words",
    category: "neutral",
  },
  sit_together: {
    emoji: "🪑",
    message: "sat quietly with you...",
    label: "sit together",
    category: "neutral",
  },
  wait: {
    emoji: "⌛",
    message: "asks you to wait a moment...",
    label: "ask to wait",
    category: "neutral",
  },
  knock: {
    emoji: "🚪",
    message: "knocked on your door!",
    label: "knock knock",
    category: "neutral",
  },
  pinky_promise: {
    emoji: "🤙",
    message: "made a pinky promise with you!",
    label: "pinky promise",
    category: "neutral",
  },
  please: {
    emoji: "🥺",
    message: "is asking nicely, please?",
    label: "ask please",
    category: "neutral",
  },
  silence: {
    emoji: "🤫",
    message: "is enjoying the silence...",
    label: "enjoy silence",
    category: "neutral",
  },
  breathe: {
    emoji: "🌬️",
    message: "took a deep breath with you...",
    label: "breathe",
    category: "neutral",
  },
  share_space: {
    emoji: "🛋️",
    message: "shared a peaceful space with you...",
    label: "share space",
    category: "neutral",
  },
  meditation: {
    emoji: "🧘",
    message: "is meditating peacefully...",
    label: "meditate",
    category: "neutral",
  },
  cloud_watching: {
    emoji: "☁️",
    message: "is watching clouds pass by...",
    label: "watch clouds",
    category: "neutral",
  },
  observe: {
    emoji: "👀",
    message: "is just observing",
    label: "observe",
    category: "neutral",
  },
  zen: {
    emoji: "⭕",
    message: "found their zen",
    label: "zen mode",
    category: "neutral",
  },
  leaf_float: {
    emoji: "🍃",
    message: "watched a leaf float by",
    label: "watch leaf",
    category: "neutral",
  },

  // Sad expressions
  cry: {
    emoji: "😢",
    message: "is crying because of you!",
    label: "cry",
    category: "sad",
  },
  cry: {
    emoji: "☹️",
    message: "is very sorry!",
    label: "say sorry",
    category: "sad",
  },
  sigh: {
    emoji: "😔",
    message: "sighed deeply at you!",
    label: "sigh",
    category: "sad",
  },
  heartbreak: {
    emoji: "💔",
    message: "feels heartbroken",
    label: "heartbreak",
    category: "sad",
  },
  lonely: {
    emoji: "🥺",
    message: "is feeling lonely",
    label: "feel lonely",
    category: "sad",
  },
  forgive_me: {
    emoji: "🙏",
    message: "asks for forgiveness",
    label: "ask forgiveness",
    category: "sad",
  },
  rain_cloud: {
    emoji: "🌧️",
    message: "has rain clouds following them",
    label: "rain cloud",
    category: "sad",
  },
  tissue: {
    emoji: "🤧",
    message: "needs a tissue",
    label: "need tissue",
    category: "sad",
  },
  rainy_day: {
    emoji: "🌧️",
    message: "is feeling gloomy on a rainy day...",
    label: "rainy day",
    category: "sad",
  },
  lost: {
    emoji: "🗺️",
    message: "feels lost and confused...",
    label: "feel lost",
    category: "sad",
  },
  violin: {
    emoji: "🎻",
    message: "plays a sad violin song",
    label: "sad violin",
    category: "sad",
  },
  goodbye: {
    emoji: "👋",
    message: "waves a sad goodbye",
    label: "sad goodbye",
    category: "sad",
  },

  // Mean expressions
  slap: {
    emoji: "🖐️",
    message: "slapped you!",
    label: "slap",
    category: "mean",
  },
  disappointed: {
    emoji: "😒",
    message: "is disappointed in you.",
    label: "disappointed",
    category: "mean",
  },
  poop: {
    emoji: "💩",
    message: "threw poop at you!",
    label: "throw poop",
    category: "mean",
  },
  shut_up: {
    emoji: "🤐",
    message: "asks you to shut up.",
    label: "ask to shut up",
    category: "mean",
  },
  throw_sand: {
    emoji: "🏖️",
    message: "threw sand at you!",
    label: "throw sand",
    category: "mean",
  },
  mock: {
    emoji: "😏",
    message: "mocked you sarcastically!",
    label: "mock",
    category: "mean",
  },
  mess_hair: {
    emoji: "💇",
    message: "messed up your hair!",
    label: "mess hair",
    category: "mean",
  },
  stick_tongue: {
    emoji: "😝",
    message: "stuck their tongue out at you!",
    label: "stick tongue out",
    category: "mean",
  },
  draw_face: {
    emoji: "✍️",
    message: "drew on your face while sleeping!",
    label: "draw on face while sleeping",
    category: "mean",
  },
  pinch: {
    emoji: "🤏",
    message: "pinched you really hard!",
    label: "pinch",
    category: "mean",
  },
  burp: {
    emoji: "🫢",
    message: "burped in your face!",
    label: "burp in face",
    category: "mean",
  },
  jail: {
    emoji: "👉🏻",
    message: "sent you to jail!",
    label: "send to jail",
    category: "mean",
  },
  fist: {
    emoji: "👊",
    message: "raised a fist at you!",
    label: "threaten",
    category: "mean",
  },
  fist: {
    emoji: "🦵🏻",
    message: "kicked your ass!",
    label: "kick ass",
    category: "mean",
  },
  ignore: {
    emoji: "🙈",
    message: "is ignoring you",
    label: "ignore",
    category: "mean",
  },
  eye_roll: {
    emoji: "🙄",
    message: "rolled their eyes at you",
    label: "roll eyes",
    category: "mean",
  },
  rage: {
    emoji: "😡",
    message: "is filled with rage!",
    label: "rage",
    category: "mean",
  },
  stomp: {
    emoji: "🦶",
    message: "angrily stomped away",
    label: "stomp away",
    category: "mean",
  },
  door_slam: {
    emoji: "🚪",
    message: "slammed the door",
    label: "slam door",
    category: "mean",
  },
  scissors: {
    emoji: "✂️",
    message: "cut you out of their life",
    label: "cut out",
    category: "mean",
  },
  talk_back: {
    emoji: "🗯️",
    message: "talked back rudely",
    label: "talk back",
    category: "mean",
  },

  // good morning
  sun: {
    emoji: "🌞",
    message: "wished you a good morning!",
    label: "good morning",
    category: "morning",
  },
  wake_up: {
    emoji: "🥁",
    message: "wants you to wake up!",
    label: "wake up!",
    category: "morning",
  },
  morning_alarm: {
    emoji: "⏰",
    message: "rings a gentle wake-up alarm!",
    label: "wake-up alarm",
    category: "morning",
  },
  morning_bed: {
    emoji: "🛏️",
    message: "helps you make the bed!",
    label: "make bed",
    category: "morning",
  },
  morning_teeth: {
    emoji: "🦷",
    message: "is brushing teeth with you!",
    label: "brush teeth",
    category: "morning",
  },
  breakfast_in_bed: {
    emoji: "🍳",
    message: "made you breakfast in bed!",
    label: "breakfast in bed",
    category: "morning",
  },
  morning_coffee: {
    emoji: "☕",
    message: "brought you morning coffee!",
    label: "morning coffee",
    category: "morning",
  },
  morning_sunshine: {
    emoji: "🌅",
    message: "opens the curtains to let sunshine in!",
    label: "morning sunshine",
    category: "morning",
  },
  morning_bird: {
    emoji: "🐦",
    message: "sings like an early bird!",
    label: "morning bird",
    category: "morning",
  },
  morning_energetic: {
    emoji: "⚡",
    message: "shares morning energy with you!",
    label: "morning energy",
    category: "morning",
  },
  morning_garden: {
    emoji: "🌺",
    message: "tends to the morning garden with you!",
    label: "morning garden",
    category: "morning",
  },

  // good night
  moon: {
    emoji: "🌙",
    message: "wished you sweet dreams!",
    label: "sweet dreams",
    category: "night",
  },
  night_story: {
    emoji: "📖",
    message: "reads you a bedtime story!",
    label: "bedtime story",
    category: "night",
  },
  night_lullaby: {
    emoji: "🎵",
    message: "sings you a lullaby!",
    label: "lullaby",
    category: "night",
  },
  night_blanket: {
    emoji: "🛏️",
    message: "tucks you in with a cozy blanket!",
    label: "tuck in",
    category: "night",
  },
  night_peaceful: {
    emoji: "✨",
    message: "wishes you peaceful dreams!",
    label: "wish peaceful dreams",
    category: "night",
  },
  night_guardian: {
    emoji: "👼",
    message: "watches over your sleep!",
    label: "sleep guardian",
    category: "night",
  },
  night_quiet: {
    emoji: "🤫",
    message: "keeps the night peaceful and quiet!",
    label: "quiet night",
    category: "night",
  },
  night_pillow: {
    emoji: "🛏️",
    message: "fluffs your pillow for better sleep!",
    label: "fluff pillow",
    category: "night",
  },
  night_stars: {
    emoji: "⭐",
    message: "admired the stars with you!",
    label: "stargazing",
    category: "night",
  },

  // Food & Drinks
  coffee: {
    emoji: "☕",
    message: "offered you a cup of coffee!",
    label: "offer coffee",
    category: "food",
  },
  tea: {
    emoji: "🫖",
    message: "invited you for tea time!",
    label: "tea time",
    category: "food",
  },
  cookie: {
    emoji: "🍪",
    message: "shared a cookie with you!",
    label: "share cookie",
    category: "food",
  },
  pizza: {
    emoji: "🍕",
    message: "wants to share pizza with you!",
    label: "share pizza",
    category: "food",
  },
  cake: {
    emoji: "🎂",
    message: "baked you a cake!",
    label: "bake cake",
    category: "food",
  },
  soup: {
    emoji: "🥣",
    message: "made you warm soup!",
    label: "make soup",
    category: "food",
  },
  ice_cream: {
    emoji: "🍦",
    message: "brought you ice cream!",
    label: "bring ice cream",
    category: "food",
  },
  boba: {
    emoji: "🧋",
    message: "brought you bubble tea!",
    label: "bubble tea",
    category: "food",
  },
  picnic: {
    emoji: "🧺",
    message: "prepared a picnic for you!",
    label: "picnic",
    category: "food",
  },
  sushi: {
    emoji: "🍱",
    message: "shared sushi with you!",
    label: "share sushi",
    category: "food",
  },
  dessert: {
    emoji: "🍮",
    message: "treated you to dessert!",
    label: "dessert treat",
    category: "food",
  },
  chocolate_bar: {
    emoji: "🍫",
    message: "shared a chocolate bar with you!",
    label: "share chocolate",
    category: "food",
  },
  smoothie: {
    emoji: "🥤",
    message: "made you a delicious smoothie!",
    label: "make smoothie",
    category: "food",
  },
  bbq: {
    emoji: "🍖",
    message: "invited you to a BBQ!",
    label: "invite to BBQ",
    category: "food",
  },
  pancakes: {
    emoji: "🥞",
    message: "made you fluffy pancakes!",
    label: "make pancakes",
    category: "food",
  },

  // Animal Vibes
  kitty: {
    emoji: "😺",
    message: "sent kitty purrs!",
    label: "kitty purr",
    category: "animals",
  },
  puppy: {
    emoji: "🐶",
    message: "sent puppy kisses!",
    label: "puppy kiss",
    category: "animals",
  },
  wag: {
    emoji: "🐕",
    message: "is wagging their tail!",
    label: "wag tail",
    category: "animals",
  },
  bird: {
    emoji: "🐦",
    message: "sent you a cheerful birdsong!",
    label: "birdsong",
    category: "animals",
  },
  butterfly: {
    emoji: "🦋",
    message: "sent butterflies your way!",
    label: "butterflies",
    category: "animals",
  },
  penguin_waddle: {
    emoji: "🐧",
    message: "waddled like a penguin!",
    label: "penguin waddle",
    category: "animals",
  },
  owl_wisdom: {
    emoji: "🦉",
    message: "shared owl wisdom!",
    label: "owl wisdom",
    category: "animals",
  },
  seal_clap: {
    emoji: "🦭",
    message: "clapped like a happy seal!",
    label: "seal clap",
    category: "animals",
  },
  dolphin_play: {
    emoji: "🐬",
    message: "played like a dolphin!",
    label: "dolphin play",
    category: "animals",
  },
  bunny_hop: {
    emoji: "🐰",
    message: "hopped like a bunny!",
    label: "bunny hop",
    category: "animals",
  },
  sloth_hug: {
    emoji: "🦥",
    message: "gave you a slow sloth hug",
    label: "sloth hug",
    category: "animals",
  },
  lion_roar: {
    emoji: "🦁",
    message: "roared like a lion!",
    label: "lion roar",
    category: "animals",
  },
  elephant_trumpet: {
    emoji: "🐘",
    message: "trumpeted like an elephant!",
    label: "elephant trumpet",
    category: "animals",
  },
  fox_sly: {
    emoji: "🦊",
    message: "acted sly like a fox!",
    label: "fox sly",
    category: "animals",
  },
  panda_roll: {
    emoji: "🐼",
    message: "rolled like a silly panda",
    label: "panda roll",
    category: "animals",
  },
  koala_cling: {
    emoji: "🐨",
    message: "clung to you like a koala",
    label: "koala cling",
    category: "animals",
  },

  // Weather Moods
  rainbow: {
    emoji: "🌈",
    message: "sent you a rainbow!",
    label: "send rainbow",
    category: "weather",
  },
  snow: {
    emoji: "❄️",
    message: "sent snowflakes your way!",
    label: "send snow",
    category: "weather",
  },
  breeze: {
    emoji: "🍃",
    message: "sent a gentle breeze!",
    label: "send breeze",
    category: "weather",
  },
  stars: {
    emoji: "✨",
    message: "is stargazing with you!",
    label: "stargaze",
    category: "weather",
  },
  thunder: {
    emoji: "⚡",
    message: "made dramatic thunder!",
    label: "make thunder",
    category: "weather",
  },
  aurora: {
    emoji: "🌌",
    message: "showed you northern lights!",
    label: "show aurora",
    category: "weather",
  },
  fog: {
    emoji: "🌫️",
    message: "created mysterious fog",
    label: "create fog",
    category: "weather",
  },
  rainbow_shower: {
    emoji: "🌦️",
    message: "made a sun shower with rainbows",
    label: "sun shower",
    category: "weather",
  },
  autumn_leaves: {
    emoji: "🍂",
    message: "scattered autumn leaves",
    label: "autumn leaves",
    category: "weather",
  },
  sunshine: {
    emoji: "☀️",
    message: "brought you warm sunshine!",
    label: "bring sunshine",
    category: "weather",
  },
  gentle_rain: {
    emoji: "🌧️",
    message: "sent gentle rain to soothe you",
    label: "gentle rain",
    category: "weather",
  },
  shooting_star: {
    emoji: "🌠",
    message: "showed you a shooting star",
    label: "shooting star",
    category: "weather",
  },
  spring_bloom: {
    emoji: "🌸",
    message: "brought spring flowers",
    label: "spring bloom",
    category: "weather",
  },
  meteor_shower: {
    emoji: "🌠",
    message: "showed you a meteor shower",
    label: "meteor shower",
    category: "weather",
  },

  // Other
  ninja: {
    emoji: "🥷",
    message: "sneaked up on you!",
    label: "ninja mode",
    category: "other",
  },
  magic: {
    emoji: "✨",
    message: "cast a magic spell!",
    label: "cast spell",
    category: "other",
  },
  forgive: {
    emoji: "🕊️",
    message: "is ready to forgive you.",
    label: "forgive",
    category: "other",
  },
  time_travel: {
    emoji: "⌛",
    message: "took you time traveling!",
    label: "time travel",
    category: "other",
  },
  walk_away: {
    emoji: "🏃‍♂️",
    message: "quietly walked away.",
    label: "walk away",
    category: "other",
  },
  run_away: {
    emoji: "🏃‍♂️",
    message: "ran away quickly!",
    label: "run away",
    category: "other",
  },
  teleport: {
    emoji: "🪄",
    message: "teleported to you!",
    label: "teleport",
    category: "other",
  },
  telepathy: {
    emoji: "🧠",
    message: "read your mind!",
    label: "telepathy",
    category: "other",
  },
  dream_travel: {
    emoji: "🛌",
    message: "took you dream traveling",
    label: "dream travel",
    category: "other",
  },
  quantum_jump: {
    emoji: "🌀",
    message: "did a quantum jump with you into parallel universe!",
    label: "quantum jump",
    category: "other",
  },
  gravity_flip: {
    emoji: "🔄",
    message: "flipped gravity upside down!",
    label: "flip gravity",
    category: "other",
  },
  time_freeze: {
    emoji: "🕰️",
    message: "froze time for a moment next to you!",
    label: "freeze time",
    category: "other",
  },
  alien_visit: {
    emoji: "👽",
    message: "brought alien friends",
    label: "alien visit",
    category: "other",
  },
  robot_dance: {
    emoji: "🤖",
    message: "did the robot dance",
    label: "robot dance",
    category: "other",
  },
  crystal_ball: {
    emoji: "🔮",
    message: "read your fortune",
    label: "fortune telling",
    category: "other",
  },
  pirate: {
    emoji: "🏴‍☠️",
    message: "sailed the seas like a pirate!",
    label: "pirate mode",
    category: "other",
  },
  superhero: {
    emoji: "🦸",
    message: "saved the day like a superhero!",
    label: "superhero mode",
    category: "other",
  },

  // reminders
  water_reminder: {
    emoji: "💧",
    message: "reminds you to drink water!",
    label: "water reminder",
    category: "reminder",
  },
  stretch_reminder: {
    emoji: "🧘‍♀️",
    message: "reminds you to stretch!",
    label: "stretch reminder",
    category: "reminder",
  },
  text_reminder: {
    emoji: "💬",
    message: "reminds you to text them!",
    label: "text me reminder",
    category: "reminder",
  },
  medicine_reminder: {
    emoji: "💊",
    message: "reminds you to take your medicine!",
    label: "medicine reminder",
    category: "reminder",
  },
  sleep_reminder: {
    emoji: "😴",
    message: "reminds you it's bedtime!",
    label: "bedtime reminder",
    category: "reminder",
  },
  meal_reminder: {
    emoji: "🍽️",
    message: "reminds you to eat!",
    label: "meal reminder",
    category: "reminder",
  },
  break_reminder: {
    emoji: "⏸️",
    message: "reminds you to take a break!",
    label: "break reminder",
    category: "reminder",
  },
  deep_breath: {
    emoji: "🫁",
    message: "reminds you to take deep breaths!",
    label: "breathing reminder",
    category: "reminder",
  },
  pet_feed: {
    emoji: "🐾",
    message: "reminds you to feed your pet!",
    label: "pet feeding",
    category: "reminder",
  },
  pet_pat: {
    emoji: "🐾",
    message: "reminds you to pet your pet!",
    label: "pet patting",
    category: "reminder",
  },
  study_reminder: {
    emoji: "📖",
    message: "reminds you to study!",
    label: "study reminder",
    category: "reminder",
  },
  dental_care: {
    emoji: "🦷",
    message: "reminds you to brush teeth!",
    label: "dental reminder",
    category: "reminder",
  },
};

module.exports = { EXPRESSION_CATEGORIES, EXPRESSIONS };
