const MOOD_CATEGORIES = [
  { key: "happy", label: "😊 happy" },
  { key: "love", label: "😍 love & affection" },
  { key: "sad", label: "😢 sad" },
  { key: "angry", label: "😠 angry" },
  { key: "anxious", label: "😰 anxious/worried" },
  { key: "tired", label: "😴 tired" },
  { key: "surprised", label: "😲 surprised/confused" },
  { key: "calm", label: "😌 calm" },
  { key: "playful", label: "😜 playful/fun" },
  { key: "confident", label: "😎 confident/proud" },
  { key: "neutral", label: "😐 neutral/other" },
];

const MOODS = {
  happy: [
    "😊 happy",
    "😄 joyful",
    "🤩 excited",
    "🥳 ecstatic",
    "😁 cheerful",
    "🌱 optimistic",
    "🌈 positive",
    "🦋 inspired",
    "🌟 encouraged",
  ],
  love: [
    "😍 in love",
    "🥰 loving",
    "💕 romantic",
    "🫂 cuddly",
    "😘 adoring",
    "💝 smitten",
    "❤️‍🔥 passionate",
    "🤱 tender",
    "🫶 caring",
  ],
  sad: [
    "😢 sad",
    "☹️ lonely",
    "😭 crying",
    "💔 heartbroken",
    "😔 melancholy",
    "🌧️ gloomy",
    "😖 miserable",
    "😫 devastated",
    "🖤 mourning",
    "😞 dejected",
  ],
  angry: [
    "😠 angry",
    "🤬 furious",
    "😤 irritated",
    "😑 annoyed",
    "😒 frustrated",
    "👿 outraged",
    "🔥 livid",
    "💢 mad",
    "🌋 heated",
    "😡 fuming",
  ],
  anxious: [
    "😰 anxious",
    "😟 worried",
    "😅 nervous",
    "😵‍💫 stressed",
    "🥺 panicked",
    "😵 overwhelmed",
    "📊 overthinking",
  ],
  tired: [
    "😴 tired",
    "🥱 exhausted",
    "😪 sleepy",
    "🫠 drained",
    "🔥 burnt out",
    "🛏️ need bed",
    "💤 sleepless",
    "🥱 yawning",
    "🧟 zombie mode",
    "📉 no energy",
    "🌙 night owl",
  ],
  surprised: [
    "😲 surprised",
    "😱 shocked",
    "🤯 amazed",
    "😕 confused",
    "🤔 puzzled",
    "😳 stunned",
    "🤷 perplexed",
    "🧐 curious",
    "😰 freaking out",
  ],
  calm: [
    "😌 calm",
    "☮️ peaceful",
    "🕊️ serene",
    "😎 relaxed",
    "😊 content",
    "😌 satisfied",
  ],
  playful: [
    "😜 playful",
    "🤪 silly",
    "🤡 goofy",
    "😏 mischievous",
    "😋 cheeky",
    "🎉 fun",
    "⚡ energetic",
    "🦘 bouncy",
    "🌈 vibrant",
    "🕺 lively",
  ],
  confident: [
    "😎 confident",
    "🦚 proud",
    "💪 determined",
    "🦁 bold",
    "🦸 brave",
    "💎 strong",
    "👑 powerful",
    "🚀 unstoppable",
  ],
  neutral: [
    "😐 neutral",
    "🙂 okay",
    "👍 fine",
    "😑 bored",
    "🤔 thoughtful",
    "💭 contemplative",
    "☁️ dreamy",
    "🌟 hopeful",
    "🎯 focused",
    "💻 productive",
  ],
};

module.exports = { MOOD_CATEGORIES, MOODS };
